name: PR

on:
  push:
    branches:
      - dev
  pull-request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          ./gradlew buildDebug